#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP.
# It accepts four parameters:
#   1. Path to the file to be transferred
#   2. IP address of the server
#   3. Username for SSH connection
#   4. Path to the SSH private key (optional)

# Check if the number of arguments provided is less than 3
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit
fi

# Transfer the file using SCP
if [ $# -ge 4 ]; then
    # If a path to the SSH private key is provided, use it
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    # If no SSH private key is provided, use the default SSH key
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
