#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo "frontend web-front
bind *:80
default_backend web-backend

backend web-backend
balance roundrobin
server web1 35.227.47.184:80 check
server web2 35.190.188.208:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start