#!/usr/bin/env bash
# displays Best School 10 times.
i=1
while [ $i -le 100 ]
do
if [ $((i%15)) = 0 ]; then
echo "FizzBuzz"
elif [ $((i%5)) = 0 ]; then
echo "Buzz"
elif [ $((i%3)) = 0 ]; then
echo "Fizz"
else
echo $i
fi
((i++))
done
