#!/usr/bin/env bash
# displays information about the school file.

i="school"
if [ -e $i ]; then
echo "school file exists"
if [ -s $i ]; then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f $i];
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
